name: ros2-rolling

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Set up ROS
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling

      # Step 2: Cache ROS dependencies
      - name: Cache ROS dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.ros
            /tmp/rosdep
            /opt/ros/rolling
          key: ${{ runner.os }}-ros2-rolling-${{ hashFiles('**/package.xml') }}-rosdep
          restore-keys: |
              ${{ runner.os }}-ros2-rolling-${{ hashFiles('**/package.xml') }}-
              ${{ runner.os }}-ros2-rolling-

      # Step 3: Run ROS CI
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: plotjuggler
          target-ros2-distro: rolling
